### ISSUE TITLE
Security check roadmap

### ISSUE THREAD

**Issue by injcristianrojas** [clcert/psifos-dockerized#1]
The following activities will be done in order to check PSIFOS platform's security:

* [x] Static analysis
  * [x] Application code
  * [x] Dependencies
  * [x] IaC (Dockerfiles)
* [x] Dynamic analysis over a dockerized version of the application in the analyzer's machine.
* [x] Direct pentest (BEWARE: Ask for permission first.)
  * [x] Test version (https://psifos.labs.clcert.cl/psifos)
  * [x] Live version (https://participauchile.cl/)
* [x] Check with Camilo if Dependabot is active in all repositories
* [x] Attempt to hack election results (false votes, etc.)
